name: EdgeConomy
version: beta_3.0
author: Panjab
authors: [lush]
website: http://edgecraft.de

depend: [EdgeCore]
loadbefore: [EdgeCuboid, EdgeJobs]

main: net.edgecraft.edgeconomy.EdgeConomy

commands:
    account:
      description: Account Command
      aliases: ['acc']
    cash:
      description: Cash Command
    credit:
      description: Credit Command
    transfer:
      description: Transfer Command
    welfare:
      description: Welfare Command
    
